#!/bin/bash

function bucket_status() {
    local bucket_name=$1
    local bucketstatus=$(aws s3api head-bucket --bucket "${bucket_name}" 2>&1)

    if [ $(echo "${bucketstatus}" | grep 'not Found') ]
    then
        echo "bucket doesn't exist";
    elif [ $(echo "${bucketstatus}" | grep 'forbidden') ]
    then
        echo "Bucket exists but not owned"
    elif [ $(echo "${bucketstatus}" | grep 'bad request') ]
    then
        echo "Bucket name specified is less than 3 or greater than 63 characters"
    else
        echo "available";
    fi
}

if [ $# -lt 2 ]
then
    echo "usage:"
    echo "deploy-to-s3 <site-folder> <bucket>"
    exit 1
fi

SITE_FOLDER=$1
BUCKET=$2

#
# Check if SITE_FOLDER is actually a folder
#
if ! [[ -d ${SITE_FOLDER} ]]
then
    echo "FATAL: ${SITE_FOLDER} is not a folder"
    exit 1
fi

#
# Check bucket availability
#
availability=$(bucket_status ${BUCKET})

if ! [[ "${availability}" == "available" ]]
then
    echo "FATAL: ${BUCKET} bucket doesn't exist or is not available"
    exit 1  
fi
#
# Sync  bucket with folder
#
AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY} aws s3 sync --delete ${SITE_FOLDER} s3://${BUCKET}



